### ISSUE TITLE
Push 2.0.5 release to pypi

### ISSUE THREAD

**Issue by melinath** [Dwolla/dwolla-python#22]
I'd like to use 2.0.5, since it has some bugfixes I need, but it doesn't seem to be available on pypi atm.

**Comment by mach-kernel** [comment]
Something strange happened with one of my build scripts. I'm going to push this out again, sorry about it! Will post back when it's done!

**Comment by mach-kernel** [comment]
@melinath it's done, [check it out here](https://pypi.python.org/pypi/dwolla)
