### ISSUE TITLE
Expose original Dwolla error on thrown exception

### ISSUE THREAD

**Issue by melinath** [Dwolla/dwolla-python#24]
Right now, there's no good way to access a Dwolla API error's original message. [It gets wrapped](https://github.com/Dwolla/dwolla-python/blob/master/dwolla/rest.py#L48) and the original isn't saved. A simple solution would be to create a simple subclass of Exception that exposes the original message as an attribute. For example:

```
class DwollaAPIException(Exception):
    def __init__(self, message, original_message):
        self.original_message = original_message
        super(DwollaAPIException, self).__init__(message, original_message)
```

This could then be used as follows:

```
if response['Success'] is not True:
    raise DwollaAPIException("dwolla-python: An API error was encountered.\nServer Message:\n" + response['Message'], response['Message'])
```

**Comment by melinath** [comment]
This would have the additional benefit of letting me more closely note which errors I'm catching vs. not.

For additional usefulness, it could be nice to just attach the original response to the thrown exception, so that I can introspect it / log it more easily. A user of my application got a "No JSON object could be decoded" error, and even if I could reproduce it, I wouldn't have any way to look at the response that caused it, since it's buried too deep in the dwolla code.

**Comment by mach-kernel** [comment]
@melinath,

You raise a very good suggestion and I'm wondering why I didn't do this in the first place. I'm a bit flogged today but I'll get to this if I have the time to by the end of the day, if not in a day or two - does that sound OK? :)

David

**Comment by mach-kernel** [comment]
@melinath, I found some spare time and got this ironed out!

Thanks for the request!

**Comment by melinath** [comment]
Great, thanks!
