### ISSUE TITLE
Expose dwollaparse option to all API methods

### ISSUE THREAD

**Issue by melinath** [Dwolla/dwolla-python#25]
Currently `Rest._post` supports a `dwollaparse` argument which determines whether the extra dwolla parsing is performed on a response or not. However, this is not exposed to the API methods. It could be useful to allow, for example, `transactions.send(dwollaparse=False, **kwargs)`. Though a little more granularity would be even better – support three options: "dwolla", "json", and `None`.

Note: this thought is to solve the same problem as I had in #24 - being able to debug / log issues with the response more thoroughly. I think I'd prefer that solution, though.

**Comment by mach-kernel** [comment]
@melinath 

Sorry for the delay with this one. I'm going to expose the toggle for `dwollaparse` in the `constants` settings file. I realize that this does not provide the granularity that you would desire - but I really want to keep the actual API query methods clean and easy to understand for beginner users. 

I want to make the move to `**kwargs`, when I do so, I will expose the `dwollaparse` to everything. I will get started on this today, as it is a better design feature. In the meantime, I have exposed this functionality in the constants file.

Going to leave this open until I release the new version. Expect it within a couple of days.

**Comment by melinath** [comment]
W/e. Like I said, for my use-case at least, I prefer having access to the raised exception, which was already resolved in b342268.

**Comment by mach-kernel** [comment]
@melinath,

You are not the only one calling for this so I'm writing an update that allows for more granular use. You can track the 2.1.3-b1 branch. I'm leaving this open if you have any other suggestions until I release in a few days.

**Comment by mach-kernel** [comment]
@melinath check the latest release out and let me know what you think. I'm interested in your feedback before closing this out.

**Comment by melinath** [comment]
@mach-kernel sorry, this got buried in my github notifications. I'll have a look at it later today or tomorrow.

**Comment by melinath** [comment]
...now that it's like three months later :-p

**Comment by mach-kernel** [comment]
That's OK, you should see my GH inbox. I can't ever find anything :p

On Thu, Sep 17, 2015 at 3:09 PM, Stephen Burrows <notifications@github.com>
wrote:

> ...now that it's like three months later :-p
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Dwolla/dwolla-python/issues/25#issuecomment-141191877>
> .
>



-- 
David Stancu
@mach-kernel <http://github.com/mach-kernel>
*Dwolla* / Developer Relations Engineer

**Comment by melinath** [comment]
Looks totally reasonable to me. :-) Don't know if I'll ever need to use it that way, but I certainly might, and now I can! Yay. A couple points of feedback:

- If I put in an invalid dwollaparse value, what happens? Looks like I'd just get None, which could be confusing.
- The docstrings for dwollaparse are incorrect: `Boolean deciding whether or not to call self._parse().` should be something explaining the three possible values.
- The README is a little unclear re: dwollaparse `dwolla` value. Currently described as: `(an extension of default, where the contents of the Response key are returned and the rest disposed).` Might be more accurate to say something like: `Returns the "Response" key for successful requests (discarding all other data) or raises a DwollaAPIException on errors.`

I hope that's useful / what you were looking for!

**Comment by mach-kernel** [comment]
@melinath thank you for your feedback. I'm going to open another issue to schedule the fixes that you described just now.
