### ISSUE TITLE
Decimal numbers cannot be passed to json

### ISSUE THREAD

**Issue by ka7eh** [Dwolla/dwolla-python#29]
By default, json.dumps doesn't serialize decimal numbers.
Suggestions for fixing this issuse:
-  Rest class can allow users to pass an Encoder class for json
- An extended version json.JSONEncoder can be provided by default. Something like this:
<pre>
class DecimalEncoder(json.JSONEncoder):
        def _iterencode(self, o, markers=None):
            if isinstance(o, decimal.Decimal):
                # wanted a simple yield str(o) in the next line,
                # but that would mean a yield on the line with super(...),
                # which wouldn't work (see my comment below), so...
                return (str(o) for o in [o])
        return super(DecimalEncoder, self)._iterencode(o, markers)
</pre>
See: http://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object

**Comment by mach-kernel** [comment]
@ka7eh,

I'm going to take a look and see if I should either:

* Do as you said, override JSONEncoder
* Switch serialization to `simplejson`

Leaning in with the former but I'm going to look into it and get back to you. Thanks for this!

**Comment by mach-kernel** [comment]
@ka7eh 

I'm assuming that you would like a custom encoder for the API endpoints? I can put something like this in `dwollaparse` but would like your input on how you would use it before I go ahead and do anything.

**Comment by mach-kernel** [comment]
@ka7eh 

My bad for deleting the two prior messages, smartphone screen and fat thumbs do not mix. I have just updated the 2.1.2 branch with the changes to fix this. Let me know if you have any other input before I publish this tonight :)

**Comment by ka7eh** [comment]
Vow, changes are happening fast! :)
Your commit looks good; I'll try the 2.1.2 branch later and see how it works with my code. Thanks.

**Comment by mach-kernel** [comment]
@ka7eh,

I tested the changes myself. Everything seems to work well so I'm going to pull the trigger on deployment. Thanks a lot for writing in with this!

**Comment by ka7eh** [comment]
@mach-kernel Just caught a bug with wrong import! :p
Created a PR for a fix: https://github.com/Dwolla/dwolla-python/pull/31
