### ISSUE TITLE
dwolla-python does not work on Google App Engine

### ISSUE THREAD

**Issue by gae123** [Dwolla/dwolla-python#34]
When calling APIs you get:

ConnectionError: ('Connection aborted.', error(13, 'Permission denied'))

Root cause is that Google App Engine sandbox does not work the requests library.

I have fixed this for another project and will attempt to fix it for this as well

**Comment by gae123** [comment]
Making good progress. I will have a pull request in the next few days.

**Comment by mach-kernel** [comment]
Thank you for your contribution. Are you wrapping around curl?

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Relations Engineer

On Sep 8, 2015, at 3:28 AM, gae123 <notifications@github.com> wrote:

Making good progress. I will have a pull request in the next few days.

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-python/issues/34#issuecomment-138460531>.

**Comment by gae123** [comment]
The Google App Engine python sandbox uses a proprietary urlfetch API (see https://cloud.google.com/appengine/docs/python/urlfetch/) to do outgoing http requests. The change is a  proxy API that either is completely transparent or if the library is on GAE it uses urlfetch instead of "requests".

**Comment by gae123** [comment]
I submitted a fix, could you pleas process it?

https://github.com/Dwolla/dwolla-python/pull/35

**Comment by mach-kernel** [comment]
@gae123 it's been merged!
